#!/usr/bin/env python3
"""Write aruco_dict.h: the 50 codes of OpenCV's DICT_4X4_50.

Each code is the marker's inner 4x4 grid read row by row from the top-left,
first cell in bit 15, white = 1. The values come from OpenCV's own marker
images, so the UI (which draws the markers) and the C detector agree.
"""
import sys
import cv2

CELL = 8
d = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
codes = []
for mid in range(50):
    img = cv2.aruco.generateImageMarker(d, mid, 6 * CELL)
    code = 0
    for r in range(6):
        for c in range(6):
            white = img[r * CELL + CELL // 2, c * CELL + CELL // 2] > 127
            if r in (0, 5) or c in (0, 5):
                assert not white, "border must be black"
            else:
                code = (code << 1) | int(white)
    codes.append(code)
assert len(set(codes)) == 50

out = sys.argv[1] if len(sys.argv) > 1 else "aruco_dict.h"
with open(out, "w") as f:
    f.write("#ifndef ARUCO_DICT_H_\n#define ARUCO_DICT_H_\n\n")
    f.write("/*\n *  aruco_dict.h\n *\n *  OpenCV DICT_4X4_50. Generated by tx/aruco/tools/gen_dict.py, do not edit.\n")
    f.write(" *  Inner 4x4 grid, row by row from the top-left, first cell in bit 15, white = 1.\n */\n\n")
    f.write("#include <stdint.h>\n\n#define AC_DICT_SIZE 50\n\n")
    f.write("static const uint16_t ac_dict[AC_DICT_SIZE] = {\n")
    for i in range(0, 50, 5):
        f.write("    " + ", ".join("0x%04X" % c for c in codes[i:i + 5]) + ",\n")
    f.write("};\n\n#endif /* ARUCO_DICT_H_ */\n")
print("wrote", out, "cv", cv2.__version__)
