// UART 시범 프로토콜: 한 줄에 JSON 이벤트 하나. 실제 하드웨어 계약은 아직 미확정이다.
const $ = id => document.getElementById(id);
const state = {chars:[], sources:[], predictions:new Map(), localPredictions:new Map(), samples:JSON.parse(localStorage.getItem('lightletter-samples')||'[]'), bins:Array(128).fill(0), port:null, reader:null, stream:null, capture:null};
function showTab(){const name=location.hash==='#review'?'review':'receive';document.querySelectorAll('.tab,.view').forEach(el=>el.classList.remove('active'));document.querySelector(`.tab[data-tab="${name}"]`).classList.add('active');$(name).classList.add('active')}
document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{location.hash=button.dataset.tab;showTab()}));
window.addEventListener('hashchange',showTab);
showTab();
function drawBins(){const canvas=$('fftChart'),c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.strokeStyle='#e7eaec';for(let y=0;y<=4;y++){c.beginPath();c.moveTo(0,y*h/4);c.lineTo(w,y*h/4);c.stroke()}const peak=Math.max(1,...state.bins);state.bins.forEach((v,i)=>{c.fillStyle='#62696f';const bh=(h-8)*v/peak;c.fillRect(i*w/128,h-bh,Math.max(1,w/128-1),bh)})}
function render(){const word=state.chars.join('');$('word').textContent=word;$('reviewWord').textContent=word;$('count').textContent=`총 ${state.chars.length}개`;$('total').textContent=state.chars.length;$('latest').textContent=state.chars.at(-1)||'—';$('latestSource').textContent=state.sources.at(-1)||'—';$('history').replaceChildren();if(!state.chars.length){$('history').innerHTML='<span class="muted">아직 수신된 문자가 없습니다.</span>'}else state.chars.slice(-20).forEach((ch,i)=>{const item=document.createElement('div');item.className='item';item.textContent=ch;item.title=state.sources[state.sources.length-Math.min(20,state.chars.length)+i]||'';const num=document.createElement('small');num.textContent=state.chars.length-Math.min(20,state.chars.length)+i+1;item.append(num);$('history').append(item)});$('reviewHistory').replaceChildren(...Array.from($('history').children,item=>item.cloneNode(true)));$('samples').replaceChildren();if(!state.samples.length)$('samples').innerHTML='<span class="muted">저장된 후보가 없습니다.</span>';else state.samples.forEach(s=>{const card=document.createElement('div');card.className='samplecard';const img=document.createElement('img');img.src=s.png;img.alt='28×28 이미지';card.append(img,document.createTextNode(`${s.label} · 예측 ${s.predicted} · ${s.id}`));$('samples').append(card)});drawBins()}
function receive(obj){$('raw').textContent=JSON.stringify(obj);$('receivedAt').textContent=new Date().toLocaleString('ko-KR');if(obj.type==='fft'){if(!Array.isArray(obj.bins)||obj.bins.length!==128||!obj.bins.every(x=>Number.isFinite(x)&&x>=0)){ $('raw').textContent='거부: FFT bins는 비음수 수치 128개여야 합니다.';return}state.bins=obj.bins;drawBins();return}if(obj.type==='recognition'){if(typeof obj.id!=='string'||typeof obj.char!=='string'||obj.char.length!==1){$('raw').textContent='거부: recognition id와 단일 문자가 필요합니다.';return}state.predictions.set(obj.id,obj.char);if(obj.crc_ok===false){$('raw').textContent+='\nCRC 실패: 누적 문자열에서 제외';return}state.chars.push(obj.char);state.sources.push('UART/FPGA');if($('captureId').value===obj.id)$('predicted').value=obj.char;render()}}
// Web Serial API는 Chromium 보안 컨텍스트에서 사용한다.
$('connect').onclick=async()=>{if(!('serial'in navigator)){alert('이 브라우저는 Web Serial을 지원하지 않습니다. macOS Chrome/Edge에서 localhost로 여세요.');return}try{state.port=await navigator.serial.requestPort();await state.port.open({baudRate:115200});$('serialStatus').textContent='연결됨';const decoder=new TextDecoder();state.reader=state.port.readable.getReader();let pending='';while(state.reader){const {value,done}=await state.reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});const lines=pending.split('\n');pending=lines.pop();for(const line of lines){try{receive(JSON.parse(line.trim()))}catch{$('raw').textContent='해석 실패: '+line.slice(0,200)}}}}catch(e){$('serialStatus').textContent='연결 실패';$('raw').textContent=String(e)}finally{state.reader?.releaseLock();state.reader=null;try{await state.port?.close()}catch{}state.port=null;$('serialStatus').textContent='연결 안 됨'}};
$('disconnect').onclick=async()=>{try{await state.reader?.cancel()}catch{}};
$('undo').onclick=()=>{state.chars.pop();state.sources.pop();render()};$('clear').onclick=()=>{state.chars=[];state.sources=[];render()};
async function refreshCameras(){if(!navigator.mediaDevices?.enumerateDevices)return;const selected=$('cameraSelect').value;const devices=(await navigator.mediaDevices.enumerateDevices()).filter(device=>device.kind==='videoinput');$('cameraSelect').replaceChildren(new Option('기본 카메라',''));devices.forEach((device,index)=>$('cameraSelect').add(new Option(device.label||`카메라 ${index+1}`,device.deviceId)));if(devices.some(device=>device.deviceId===selected))$('cameraSelect').value=selected}
async function startCamera(){if(state.stream)return;if(!navigator.mediaDevices?.getUserMedia)throw new Error('카메라 API를 사용할 수 없습니다. localhost에서 여세요.');const id=$('cameraSelect').value;state.stream=await navigator.mediaDevices.getUserMedia({video:id?{deviceId:{exact:id}}:true,audio:false});const video=$('video');video.srcObject=state.stream;video.onloadedmetadata=()=>{video.closest('.camera').style.aspectRatio=`${video.videoWidth}/${video.videoHeight}`;$('cameraEmpty').style.display='none'};video.style.display='block';await video.play();await refreshCameras().catch(()=>{});const activeId=state.stream.getVideoTracks()[0]?.getSettings().deviceId;if(activeId&&[...$('cameraSelect').options].some(option=>option.value===activeId))$('cameraSelect').value=activeId}
function stopCamera(){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;const video=$('video');video.srcObject=null;video.style.display='none';$('cameraEmpty').style.display='block';video.closest('.camera').style.aspectRatio='4/3'}
$('cameraStart').onclick=async()=>{try{await startCamera()}catch(error){$('reviewMessage').textContent='카메라 권한 또는 연결 실패: '+error.message}};
$('cameraStop').onclick=stopCamera;
$('cameraRefresh').onclick=()=>refreshCameras().catch(error=>$('reviewMessage').textContent='카메라 목록 조회 실패: '+error.message);
$('cameraSelect').onchange=async()=>{if(!state.stream)return;stopCamera();try{await startCamera()}catch(error){$('reviewMessage').textContent='카메라 전환 실패: '+error.message}};
refreshCameras().catch(()=>{});
navigator.mediaDevices?.addEventListener?.('devicechange',()=>refreshCameras().catch(()=>{}));
async function capturePhoto(){const v=$('video'),message=$('reviewMessage');if(!state.stream||!v.videoWidth){message.textContent='먼저 카메라를 켜세요.';return}const side=Math.min(v.videoWidth,v.videoHeight),sx=(v.videoWidth-side)/2,sy=(v.videoHeight-side)/2;const source=document.createElement('canvas');source.width=source.height=224;source.getContext('2d').drawImage(v,sx,sy,side,side,0,0,224,224);const canvas=$('preview'),c=canvas.getContext('2d',{willReadFrequently:true});c.drawImage(source,0,0,28,28);const data=c.getImageData(0,0,28,28);const pixels=[];for(let i=0;i<data.data.length;i+=4){const gray=Math.round(.299*data.data[i]+.587*data.data[i+1]+.114*data.data[i+2]);const modelPixel=gray>=128?255:0;data.data[i]=data.data[i+1]=data.data[i+2]=modelPixel;pixels.push(modelPixel)}c.putImageData(data,0,0);const id='capture-'+Date.now();state.capture={id,pixels,png:canvas.toDataURL('image/png'),sourceJpeg:source.toDataURL('image/jpeg',.8),time:new Date().toISOString(),preprocess:'center-square-resize28-grayscale-threshold128-black0-white1-v2'};$('captureId').value=id;$('predicted').value='';$('sampleStatus').textContent='로컬 CNN 추론 중…';message.textContent='로컬 CNN 추론 중…';try{const response=await fetch('/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pixels})});const result=await response.json();if(!response.ok)throw new Error(result.error||'추론 실패');if(state.capture?.id!==id)return;state.localPredictions.set(id,result.char);$('predicted').value=result.char;$('sampleStatus').textContent=`로컬 CNN 예측: ${result.char} (${(result.confidence*100).toFixed(1)}%)`;state.chars.push(result.char);state.sources.push('Mac 임시 CNN');$('receivedAt').textContent=new Date().toLocaleString('ko-KR');message.textContent=`임시 인식 결과 ${result.char}를 누적 문자열에 추가했습니다. FPGA/광통신 수신 결과는 아닙니다.`;render()}catch(error){$('sampleStatus').textContent='캡처 완료 · CNN 예측 실패';message.textContent=`로컬 추론 서버를 실행하세요: ${error.message}`}}
$('capture').onclick=capturePhoto;
$('captureId').oninput=()=>{$('predicted').value=state.predictions.get($('captureId').value)||state.localPredictions.get($('captureId').value)||''};
$('saveLabel').onclick=()=>{const id=$('captureId').value.trim(),predicted=state.predictions.get(id)||state.localPredictions.get(id),source=state.predictions.has(id)?'uart-fpga':'local-pytorch-qat16',label=$('label').value.trim().toUpperCase();if(!state.capture||state.capture.id!==id){$('reviewMessage').textContent='현재 캡처의 ID를 사용하세요.';return}if(!predicted){$('reviewMessage').textContent='해당 촬영 ID의 CNN 예측이 아직 없습니다.';return}if(!/^[A-Z0-9]$/.test(label)){ $('reviewMessage').textContent='정답은 대문자 A–Z 또는 숫자 0–9 한 글자여야 합니다.';return}if(label===predicted.toUpperCase()){$('reviewMessage').textContent='예측과 정답이 같습니다. 오탐 후보로 저장하지 않았습니다.';return}if(state.samples.some(s=>s.id===id)){$('reviewMessage').textContent='이미 저장된 촬영 ID입니다.';return}const next=[...state.samples,{...state.capture,id,predicted,predictionSource:source,label}];try{localStorage.setItem('lightletter-samples',JSON.stringify(next));state.samples=next}catch{$('reviewMessage').textContent='브라우저 저장 공간이 부족합니다. 먼저 JSON을 내보내 백업하세요.';return}$('reviewMessage').textContent='오탐 후보를 브라우저에 저장했습니다. 오프라인 재학습은 수행하지 않았습니다.';render()};
function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('export').onclick=()=>download('lightletter-misclassifications.json',new Blob([JSON.stringify({schema:'lightletter-v0',samples:state.samples},null,2)],{type:'application/json'}));
$('exportPng').onclick=()=>{if(!state.capture){$('reviewMessage').textContent='먼저 이미지를 캡처하세요.';return}fetch(state.capture.png).then(r=>r.blob()).then(b=>download(($('captureId').value||'capture')+'-28x28.png',b))};
render();
